ДЗ№6
DimaMasal0v/2024-2-VK-EDU-Frontend-D-Masalov pull request #7
Opened 2024-11-21 18:37 UTC by DimaMasal0v

# Домашнее задание №6
Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
Подключил react-router
Настроил маршрутизацию для своих страниц
Сверстал Страницу профиля

2024-11-23 09:51 UTC, kgrechin requested changes
@DimaMasal0v 

<img width="1680" alt="Снимок экрана 2024-11-23 в 12 49 31" src="https://github.com/user-attachments/assets/9a374366-a5bf-4544-8ec1-2ac39f4c2252">

пожалуйста поправь деплой, должна быть страница чатов и отдельного чата

2024-11-29 06:25 UTC, kgrechin commented
@DimaMasal0v

2024-12-06 16:36 UTC, kgrechin submitted a review, later dismissed
@DimaMasal0v, деплой я поправил, пожалуйста поправь навигацию между страницами, чтобы открывалис чаты, и картинки для юзеров подгружались, подлей  себе эту ветку git pull origin dz6 в ветке либо git branch -D dz6 && git switch master && git pull origin master && git switch dz6

2025-01-17 09:46 UTC, martinkomitsky commented
7

2025-01-17 09:46 UTC, martinkomitsky approved these changes

2025-01-17 09:46 UTC, merged